inputs_def:
  - handle: id
    description: Input
    json_schema:
      type: string
  - handle: documents
    json_schema:
      type: string
      ui:widget: dir
    nullable: false
  - handle: limit
    json_schema:
      type: integer
      exclusiveMinimum: 0
    nullable: true
    value:
outputs_def:
  - handle: highlights
    json_schema:
      type: array
      items:
        type: object
        additionalProperties: false
        required:
          - id
          - selected
          - representative
          - created_at
          - updated_at
        properties:
          id:
            type: string
          epubcfi:
            type: string
          note:
            type: string
          selected:
            type: string
          representative:
            type: string
          created_at:
            type: number
          updated_at:
            type: number
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Read highlights
